### ISSUE TITLE
Реализовать счётчик найденных пасхалок

### ISSUE THREAD

**Issue by Assargadon** [hackerembassy/hackerembassy#10]
Мне кажется, что добавлять всё новые и новые пасхалки на сайт - это хорошая, годная традиция.

Предлагаю реализовать счётчик найденных пасхалок:
- [x] ключ `"easter_eggs_found"` в `localStorage`, значение - сериализованный set идентификаторов найденных пасхалок.
- [x] каждая пасхалка при активации дописывает туда свой идентификатор. В самой пасхалке он может храниться в зашифрованном виде
- [x] где-то на сайте (в футере?) выводится число (а может и список идентификаторов) найденных пасхалок.

**Comment by tectonick** [comment]
Хорошая идея. И больше пасхалок, у меня есть еще на уме

**Comment by tectonick** [comment]
Развил идею как Стим ачивки)
