### ISSUE TITLE
Больше актуальных фоток

### ISSUE THREAD

**Issue by Assargadon** [hackerembassy/hackerembassy#11]
Сейчас на сайте 6 фоток, из которых 3 - фотографии 3Д-принтера, а ещё одна - фотография ноутбука, играющего роль сервера 3Д-печати. Нужно разнообразить это, _как минимум_:
- [x] фоткой второго этажа с пуфиками
- [x] фоткой понедельничного музыкального собрания с гитарами
- [x] фоткой "электронного счастья": паяльная станция/блок питания/тестер(ы)/ардуино-набора/набора шлейфов. Всё в одном кадре в смысле.

Возможно имеет смысл называть фотографии по (ориентировочной) дате их появления. Чтобы в будущем можно было своевременно обновлять их.

**Comment by tectonick** [comment]
Надо будет немного пофоткать

**Comment by tectonick** [comment]
Новые фотки добавлены (+ одна пасхалка).
