### ISSUE TITLE
Ленточка "Fork me"

### ISSUE THREAD

**Issue by astynax** [hackerembassy/hackerembassy#20]
Раз уж исходники сайта открыто лежат на GH, было бы приятно иметь классическую ленточку "Fork me": https://github.blog/2008-12-19-github-ribbons/

**Comment by tectonick** [comment]
Боюсь, что она не впишется в дизайн сайта и будет лишней. К тому же, не думаю, что кому-либо понадобится форкать наш сайт, нам проще принимать contribution через реквесты напрямую в наш репозиторий от мемберов организации (все из них имеют прямой доступ к нему)

**Comment by astynax** [comment]
Дело не в призыве форкать как в таковом, просто так часто показывают, что можно посмотреть на исходники сайта там-то. Но ок, то, что в дизайн вписать сложно может быть, я могу понять. Может быть просто где-то в подвале ссылку дать на организацию в GH?

**Comment by tectonick** [comment]
Добавил ссылку на организацию, теперь в разделе контактов

**Comment by astynax** [comment]
:+1:
