### ISSUE TITLE
Карта не отображается в Firefox

### ISSUE THREAD

**Issue by Assargadon** [hackerembassy/hackerembassy#5]
Я вижу код подключения яндекс-карт, но по факту отображается (в Firefox) вот так:
![изображение](https://user-images.githubusercontent.com/1663097/209478027-f5986e50-a4fc-477e-82f3-81f38a0a3f4e.png)

**Comment by tectonick** [comment]
Не могу воспроизвести в Firefox, Chrome и Edge

**Comment by Assargadon** [comment]
В Chromium отображается
![Снимок экрана от 2022-12-25 21-08-48](https://user-images.githubusercontent.com/1663097/209478155-bc9d9ea0-18fb-404a-87a5-49d789fab4b6.png)

**Comment by Assargadon** [comment]
Нашёл сообщение об ошибке:

![Снимок экрана от 2022-12-26 00-25-52](https://user-images.githubusercontent.com/1663097/209482323-2044afc9-e545-4445-a3a7-3f6e79a3595e.png)

**Comment by tectonick** [comment]
@Assargadon воспроизводится ли еще? У меня в firefox все отображается 
![image](https://user-images.githubusercontent.com/23328943/219902882-e1ebe6fd-0ea5-4b76-97ee-a28fa31f0d61.png)

**Comment by tectonick** [comment]
Теперь карта OSM вместо Яндекса
